name: Welcome Discussion Comment

on:
  discussion:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on new discussion
        
        with:
          script: |
            github.rest.discussions.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              discussion_number: context.payload.discussion.number,
              body: "Welcome to the discussion! Thanks for starting a conversation."
            });